# Generated by Django 3.2.5 on 2021-09-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifbuild',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата'),
        ),
    ]
